// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/[slug]/chapter/[chapter].ts";
import * as $1 from "./routes/api/[slug]/index.ts";
import * as $2 from "./routes/api/index.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/ChapterRead.tsx";
import * as $$1 from "./islands/MangaDetails.tsx";
import * as $$2 from "./islands/MangaList.tsx";
import * as $$3 from "./islands/Pagination.tsx";

const manifest = {
  routes: {
    "./routes/api/[slug]/chapter/[chapter].ts": $0,
    "./routes/api/[slug]/index.ts": $1,
    "./routes/api/index.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/ChapterRead.tsx": $$0,
    "./islands/MangaDetails.tsx": $$1,
    "./islands/MangaList.tsx": $$2,
    "./islands/Pagination.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
